data_directory:
  temporary_json_data_store: "/home/ansary/work/apsis/DocSignerNML/resources/tmp_data_store"
  document_design_resource_path: "/home/ansary/work/apsis/DocSignerNML/resources/document_templates_and_designs"


max_context_tokens: 131072 


generation_config: 
  simplify: 
    temperature: 
    repeation_penalty:
    frequency_penalty: 
    max_tokens: 
    max_token_redunction: 
  recommend:
    temperature:
    max_tokens: 
  risk_analysis:
    get_logits:
  ......
  .......
  .......
  .......
  .......