"""Create initial tables

Revision ID: f631cdec6b3c
Revises: 
Create Date: 2025-09-10 19:17:38.757036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f631cdec6b3c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('envelopes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('draft', 'sent', 'completed', 'voided', name='envelope_status_enum'), nullable=False),
    sa.Column('original_doc_path', sa.String(), nullable=False),
    sa.Column('original_doc_hash', sa.String(), nullable=False),
    sa.Column('signed_doc_path', sa.String(), nullable=True),
    sa.Column('final_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_trails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('envelope_id', sa.String(length=36), nullable=False),
    sa.Column('event', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['envelope_id'], ['envelopes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_trails_id'), 'audit_trails', ['id'], unique=False)
    op.create_table('recipients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('envelope_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('signing_order', sa.Integer(), nullable=False),
    sa.Column('signing_token', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'viewed', 'signed', name='recipient_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['envelope_id'], ['envelopes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipients_email'), 'recipients', ['email'], unique=False)
    op.create_index(op.f('ix_recipients_id'), 'recipients', ['id'], unique=False)
    op.create_index(op.f('ix_recipients_signing_token'), 'recipients', ['signing_token'], unique=True)
    op.create_table('fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('envelope_id', sa.String(length=36), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('signature', 'initial', 'date', 'text', 'checkbox', name='field_type_enum'), nullable=False),
    sa.Column('x_coord', sa.Float(), nullable=False),
    sa.Column('y_coord', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['envelope_id'], ['envelopes.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['recipients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fields_id'), 'fields', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fields_id'), table_name='fields')
    op.drop_table('fields')
    op.drop_index(op.f('ix_recipients_signing_token'), table_name='recipients')
    op.drop_index(op.f('ix_recipients_id'), table_name='recipients')
    op.drop_index(op.f('ix_recipients_email'), table_name='recipients')
    op.drop_table('recipients')
    op.drop_index(op.f('ix_audit_trails_id'), table_name='audit_trails')
    op.drop_table('audit_trails')
    op.drop_table('envelopes')
    # ### end Alembic commands ###
